apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    jsonData:
      tracesToLogsV2:
        datasourceUid: 'Loki'
        tags:
          - job
        mappedTags:
          - key: 'service.name'
            value: 'service.name'
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        filterBySpanID: false
      nodeGraph:
        enabled: true
      tracesToMetrics:
        datasourceUid: 'Prometheus'
        tags:
          - key: 'service.name'
            value: 'service.name'
        queries:
          - name: 'Sample query'
            query: 'sum(rate(http_server_requests_seconds_count{service="$service.name"}[5m]))'
