// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: smartbudget.proto

package smartbudgetpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BudgetSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BudgetSummaryRequest) Reset() {
	*x = BudgetSummaryRequest{}
	mi := &file_smartbudget_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetSummaryRequest) ProtoMessage() {}

func (x *BudgetSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smartbudget_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetSummaryRequest.ProtoReflect.Descriptor instead.
func (*BudgetSummaryRequest) Descriptor() ([]byte, []int) {
	return file_smartbudget_proto_rawDescGZIP(), []int{0}
}

func (x *BudgetSummaryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type BudgetSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*CategorySummary     `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BudgetSummaryResponse) Reset() {
	*x = BudgetSummaryResponse{}
	mi := &file_smartbudget_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetSummaryResponse) ProtoMessage() {}

func (x *BudgetSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_smartbudget_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetSummaryResponse.ProtoReflect.Descriptor instead.
func (*BudgetSummaryResponse) Descriptor() ([]byte, []int) {
	return file_smartbudget_proto_rawDescGZIP(), []int{1}
}

func (x *BudgetSummaryResponse) GetCategories() []*CategorySummary {
	if x != nil {
		return x.Categories
	}
	return nil
}

type CategorySummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Total         float64                `protobuf:"fixed64,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategorySummary) Reset() {
	*x = CategorySummary{}
	mi := &file_smartbudget_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategorySummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategorySummary) ProtoMessage() {}

func (x *CategorySummary) ProtoReflect() protoreflect.Message {
	mi := &file_smartbudget_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategorySummary.ProtoReflect.Descriptor instead.
func (*CategorySummary) Descriptor() ([]byte, []int) {
	return file_smartbudget_proto_rawDescGZIP(), []int{2}
}

func (x *CategorySummary) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CategorySummary) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CategoryExpensesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryExpensesRequest) Reset() {
	*x = CategoryExpensesRequest{}
	mi := &file_smartbudget_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryExpensesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryExpensesRequest) ProtoMessage() {}

func (x *CategoryExpensesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smartbudget_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryExpensesRequest.ProtoReflect.Descriptor instead.
func (*CategoryExpensesRequest) Descriptor() ([]byte, []int) {
	return file_smartbudget_proto_rawDescGZIP(), []int{3}
}

func (x *CategoryExpensesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CategoryExpensesRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type CategoryExpensesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Total         float64                `protobuf:"fixed64,2,opt,name=total,proto3" json:"total,omitempty"`
	Payments      []*PaymentInfo         `protobuf:"bytes,3,rep,name=payments,proto3" json:"payments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryExpensesResponse) Reset() {
	*x = CategoryExpensesResponse{}
	mi := &file_smartbudget_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryExpensesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryExpensesResponse) ProtoMessage() {}

func (x *CategoryExpensesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_smartbudget_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryExpensesResponse.ProtoReflect.Descriptor instead.
func (*CategoryExpensesResponse) Descriptor() ([]byte, []int) {
	return file_smartbudget_proto_rawDescGZIP(), []int{4}
}

func (x *CategoryExpensesResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CategoryExpensesResponse) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CategoryExpensesResponse) GetPayments() []*PaymentInfo {
	if x != nil {
		return x.Payments
	}
	return nil
}

type PaymentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Service       string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentInfo) Reset() {
	*x = PaymentInfo{}
	mi := &file_smartbudget_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentInfo) ProtoMessage() {}

func (x *PaymentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_smartbudget_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentInfo.ProtoReflect.Descriptor instead.
func (*PaymentInfo) Descriptor() ([]byte, []int) {
	return file_smartbudget_proto_rawDescGZIP(), []int{5}
}

func (x *PaymentInfo) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *PaymentInfo) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentInfo) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *PaymentInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_smartbudget_proto protoreflect.FileDescriptor

const file_smartbudget_proto_rawDesc = "" +
	"\n" +
	"\x11smartbudget.proto\x12\vsmartbudget\x1a\x1cgoogle/api/annotations.proto\"/\n" +
	"\x14BudgetSummaryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"U\n" +
	"\x15BudgetSummaryResponse\x12<\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x1c.smartbudget.CategorySummaryR\n" +
	"categories\"C\n" +
	"\x0fCategorySummary\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x01R\x05total\"N\n" +
	"\x17CategoryExpensesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\"\x82\x01\n" +
	"\x18CategoryExpensesResponse\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x01R\x05total\x124\n" +
	"\bpayments\x18\x03 \x03(\v2\x18.smartbudget.PaymentInfoR\bpayments\"\x95\x01\n" +
	"\vPaymentInfo\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt2\xb7\x02\n" +
	"\x12SmartBudgetService\x12\x84\x01\n" +
	"\x10GetBudgetSummary\x12!.smartbudget.BudgetSummaryRequest\x1a\".smartbudget.BudgetSummaryResponse\")\x82\xd3\xe4\x93\x02#\x12!/v1/smartbudget/summary/{user_id}\x12\x99\x01\n" +
	"\x13GetCategoryExpenses\x12$.smartbudget.CategoryExpensesRequest\x1a%.smartbudget.CategoryExpensesResponse\"5\x82\xd3\xe4\x93\x02/\x12-/v1/smartbudget/expenses/{user_id}/{category}BRZPgithub.com/tomiristapen/banking_service/smart_budget_service/proto;smartbudgetpbb\x06proto3"

var (
	file_smartbudget_proto_rawDescOnce sync.Once
	file_smartbudget_proto_rawDescData []byte
)

func file_smartbudget_proto_rawDescGZIP() []byte {
	file_smartbudget_proto_rawDescOnce.Do(func() {
		file_smartbudget_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_smartbudget_proto_rawDesc), len(file_smartbudget_proto_rawDesc)))
	})
	return file_smartbudget_proto_rawDescData
}

var file_smartbudget_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_smartbudget_proto_goTypes = []any{
	(*BudgetSummaryRequest)(nil),     // 0: smartbudget.BudgetSummaryRequest
	(*BudgetSummaryResponse)(nil),    // 1: smartbudget.BudgetSummaryResponse
	(*CategorySummary)(nil),          // 2: smartbudget.CategorySummary
	(*CategoryExpensesRequest)(nil),  // 3: smartbudget.CategoryExpensesRequest
	(*CategoryExpensesResponse)(nil), // 4: smartbudget.CategoryExpensesResponse
	(*PaymentInfo)(nil),              // 5: smartbudget.PaymentInfo
}
var file_smartbudget_proto_depIdxs = []int32{
	2, // 0: smartbudget.BudgetSummaryResponse.categories:type_name -> smartbudget.CategorySummary
	5, // 1: smartbudget.CategoryExpensesResponse.payments:type_name -> smartbudget.PaymentInfo
	0, // 2: smartbudget.SmartBudgetService.GetBudgetSummary:input_type -> smartbudget.BudgetSummaryRequest
	3, // 3: smartbudget.SmartBudgetService.GetCategoryExpenses:input_type -> smartbudget.CategoryExpensesRequest
	1, // 4: smartbudget.SmartBudgetService.GetBudgetSummary:output_type -> smartbudget.BudgetSummaryResponse
	4, // 5: smartbudget.SmartBudgetService.GetCategoryExpenses:output_type -> smartbudget.CategoryExpensesResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_smartbudget_proto_init() }
func file_smartbudget_proto_init() {
	if File_smartbudget_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_smartbudget_proto_rawDesc), len(file_smartbudget_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_smartbudget_proto_goTypes,
		DependencyIndexes: file_smartbudget_proto_depIdxs,
		MessageInfos:      file_smartbudget_proto_msgTypes,
	}.Build()
	File_smartbudget_proto = out.File
	file_smartbudget_proto_goTypes = nil
	file_smartbudget_proto_depIdxs = nil
}
