// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: proto/smartbudget.proto

package smartbudgetpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SmartBudgetService_GetBudgetSummary_FullMethodName    = "/smartbudget.SmartBudgetService/GetBudgetSummary"
	SmartBudgetService_GetCategoryExpenses_FullMethodName = "/smartbudget.SmartBudgetService/GetCategoryExpenses"
)

// SmartBudgetServiceClient is the client API for SmartBudgetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SmartBudgetServiceClient interface {
	GetBudgetSummary(ctx context.Context, in *BudgetSummaryRequest, opts ...grpc.CallOption) (*BudgetSummaryResponse, error)
	GetCategoryExpenses(ctx context.Context, in *CategoryExpensesRequest, opts ...grpc.CallOption) (*CategoryExpensesResponse, error)
}

type smartBudgetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSmartBudgetServiceClient(cc grpc.ClientConnInterface) SmartBudgetServiceClient {
	return &smartBudgetServiceClient{cc}
}

func (c *smartBudgetServiceClient) GetBudgetSummary(ctx context.Context, in *BudgetSummaryRequest, opts ...grpc.CallOption) (*BudgetSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BudgetSummaryResponse)
	err := c.cc.Invoke(ctx, SmartBudgetService_GetBudgetSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartBudgetServiceClient) GetCategoryExpenses(ctx context.Context, in *CategoryExpensesRequest, opts ...grpc.CallOption) (*CategoryExpensesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CategoryExpensesResponse)
	err := c.cc.Invoke(ctx, SmartBudgetService_GetCategoryExpenses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SmartBudgetServiceServer is the server API for SmartBudgetService service.
// All implementations must embed UnimplementedSmartBudgetServiceServer
// for forward compatibility.
type SmartBudgetServiceServer interface {
	GetBudgetSummary(context.Context, *BudgetSummaryRequest) (*BudgetSummaryResponse, error)
	GetCategoryExpenses(context.Context, *CategoryExpensesRequest) (*CategoryExpensesResponse, error)
	mustEmbedUnimplementedSmartBudgetServiceServer()
}

// UnimplementedSmartBudgetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSmartBudgetServiceServer struct{}

func (UnimplementedSmartBudgetServiceServer) GetBudgetSummary(context.Context, *BudgetSummaryRequest) (*BudgetSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBudgetSummary not implemented")
}
func (UnimplementedSmartBudgetServiceServer) GetCategoryExpenses(context.Context, *CategoryExpensesRequest) (*CategoryExpensesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCategoryExpenses not implemented")
}
func (UnimplementedSmartBudgetServiceServer) mustEmbedUnimplementedSmartBudgetServiceServer() {}
func (UnimplementedSmartBudgetServiceServer) testEmbeddedByValue()                            {}

// UnsafeSmartBudgetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SmartBudgetServiceServer will
// result in compilation errors.
type UnsafeSmartBudgetServiceServer interface {
	mustEmbedUnimplementedSmartBudgetServiceServer()
}

func RegisterSmartBudgetServiceServer(s grpc.ServiceRegistrar, srv SmartBudgetServiceServer) {
	// If the following call pancis, it indicates UnimplementedSmartBudgetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SmartBudgetService_ServiceDesc, srv)
}

func _SmartBudgetService_GetBudgetSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BudgetSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartBudgetServiceServer).GetBudgetSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartBudgetService_GetBudgetSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartBudgetServiceServer).GetBudgetSummary(ctx, req.(*BudgetSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartBudgetService_GetCategoryExpenses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryExpensesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartBudgetServiceServer).GetCategoryExpenses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartBudgetService_GetCategoryExpenses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartBudgetServiceServer).GetCategoryExpenses(ctx, req.(*CategoryExpensesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SmartBudgetService_ServiceDesc is the grpc.ServiceDesc for SmartBudgetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SmartBudgetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "smartbudget.SmartBudgetService",
	HandlerType: (*SmartBudgetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBudgetSummary",
			Handler:    _SmartBudgetService_GetBudgetSummary_Handler,
		},
		{
			MethodName: "GetCategoryExpenses",
			Handler:    _SmartBudgetService_GetCategoryExpenses_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/smartbudget.proto",
}
